### ISSUE TITLE
Shipped with unaccessible functions

### ISSUE THREAD

**Issue by ElCapor** [cstom4994/imgui_lua_inspector#1]
This code uses a ton of functions that are specific to your engine (neko engine perhaps) , and as a result , fails to compile, unless one makes heavy tweaks and recreate the funcs.

example : neko_inline, neko_lua_equal

Solution : please provide or remove these functions thanks !

Apart from that nice project 👍

**Comment by ElCapor** [comment]
rgba_to_imvec
neko_assert

**Comment by ElCapor** [comment]
neko_bool_str too

**Comment by ElCapor** [comment]
C:\Users\HP\Desktop\Programming\Il2CppLua\extern\vendor\lua_inspector\imgui_lua_inspector.hpp(74): note: may be 'bool neko::neko_lua_equal(lua_State *,const Iterable &)'
extern\vendor\lua_inspector\imgui_lua_inspector.cpp(181): note: 'bool neko::neko_lua_equal(lua_State *,const Iterable 
&)' : expects arguments 2 - 3 to be supplied.

**Comment by ElCapor** [comment]
thanks in advance

**Comment by cstom4994** [comment]
Hello, thank you for your feedback.
The above error has been fixed and an example that can be run directly (by xmake) has been added.

![image](https://github.com/cstom4994/imgui_lua_inspector/assets/22556792/972b369a-d6d6-48ea-9a24-67a30c5ea9ff)
